sailfishos/sailfish-office

models/documentlistmodel.cpp, models/documentlistmodel.h, models/trackerdocumentprovider.cpp
The purpose of these two commits is to avoid to call clear() on the model when tracker signal a change in the list of documents.
To do this, the searchFinished() function has been modified to update the current list model instead of clearing it and rebuild it. There are three things to do :
* add new entries (already done by addItem()) ;
* update already existing entries (think new document of a different type, replacing an old one) ;
* remove entries not in tracker list anymore.
The second point is changed in addItem() to update when finding an already existing entry. The third is done via a new boolean in the structure DocumentListModelEntry.
Quickly tested on my device, it solve the issue #10 and avoid in addition the flicking of the list when a document is removed / added.
=> Proposed solution to solve issue #10

pdf/pdfdocument.cpp, pdf/pdfdocument.h, pdf/pdfjob.cpp, pdf/pdfrenderthread.cpp, pdf/pdfrenderthread.h, plugin/PDFDocumentPage.qml
Proposed patches to avoid crashes when tapping on a broken PDF file (issue #21).
I've :
- protected all calls to attributes of Poppler::Document when it is a null pointer because of loading failure at pdfjob.cpp:31.
- added a flag in PdfRenderThread that becomes true when file loading results in a null pointer and expose it read only in PdfDocument.
- used this flag in QML to return to document list when tapping on a broken PDF file and notify the user.
What do you think ? I don't like much the fact that the page for the PDF file is pushed and then popped immediately, but I don't know what to show otherwise. On the other side, that would be nice to still have the drawer at hand even for broken PDF files, because we may want to forward them by email for investigation…
=> Notify user on broken PDF files

pdf/pdfcanvas.cpp, pdf/pdfdocument.cpp, pdf/pdfdocument.h, pdf/pdfjob.cpp, pdf/pdfjob.h, pdf/pdfrenderthread.cpp, pdf/pdfrenderthread.h, plugin/PDFDocumentPage.qml
I've wrapped thePoppler::Document::unlock() method in Pdf::Document (through a call in background) and add a requestUnLock() method for Pdf::Document objects.
The UI has been updated in accordance to be able to enter password for encrypted PDF files. This is done through a ViewPlaceholder in the PDFView object.
The previously introduced notification for broken PDF has been removed in favour of this new ViewPlaceholder.
This pull request partially address issue #1 for PDF documents.
=> [sailfish-office] Add the ability to unlock password encrypted PDF documents

CMakeLists.txt, models/filtermodel.cpp, models/filtermodel.h, qml/FileListPage.qml, qml/SearchPageHeader.qml, sailfishapplication.cpp
This pull request adds the capability to filter the document list to display a subpart of all documents on the phone. The filtering is done on file names only. The model is filtered when matching a subpart of the filename. This is convenient for instance to find a specific document, like when look for electricity bills or whatever.
I've added a QSortFilterProxyModel on the cpp side that works on DocumentListModel object. It is exported as a QML type "FilterModel".
I've added a SearchPageHeader QML component, inspired by the one of the media player (for UI consistency). This component displays a PageHeader or a SearchField. The SearchField is activated through a pulley menu.
What do you think ?
=> [sailfish-office] Filter the document list with a search field

plugin/PDFView.qml
This pull request addresses the issue #17. This is done in the two on{Width,Height}Changed signal handlers of the PDFView component.
It also corrects an other inconsistency in the zoom level when device is rotated :
* open a PDF in portrait mode ;
* rotate the device, the width is adjusted to the new screen width, that's fine.
But :
* return to portrait mode (width is again adjusted, fine) ;
* zoom in a bit, some pixels ;
* rotate the device, the zoom level is conserved and the view is not anymore within [width;2.5 × width]
Any aditional zoom change will jump into this range.
This is due to the fact that the zoom function remove the binding between pdfCanvas.width and base.width and the [width;2.5 × width] constraint is only applied on zoom.
The rest of the pull request correct this by …
=> [office] Adjust content position when device is rotated and zoom level changes.

plugin/PDFView.qml
There is an issue with PDF files with many pages when zooming in or out near the end of the file. To reproduce :
* open a PDF file with many pages like http://www.free.fr/adsl/pdf/cgv-forfait-hors-opt-11072007.pdf ;
* jump to the last page and stay at the bottom;
* zoom in and out, from time to time, the view is jumping up and down.
This is due to two factors in the code :
* the zooming factor is not the same for the width and the height. Indeed, the height is cast to an int in pdfcanvas.cpp, so a rounding appears here ;
* the fact of affacting contentX to a new value in PDFView.qml zoom() function makes contentY changes also (I guess because height has changed and the view is adjusting its contentY accordingly to a value that makes the bottom part of the document stays at the bottom of …
=> [office] correct an issue of content jumping when zooming near the end of long PDF files.

pdf/pdftocmodel.cpp, pdf/pdftocmodel.h, plugin/PDFDocumentToCPage.qml
This adds a message for empty index page for PDF documents instead of showing an empty page.
The enabled attribute of the placeholder is not set by binding since the tocmodel object comes from a different thread and QML complains about signaling from a different thread. Thus, enabled attribute is set by javascript by reading the count value when model is set instead.
=> [office] Add a placeholder for the table of content of PDF documents.

qml/FileListPage.qml
This pull request should correct the focus issue #33. It also use an appropriated message when the list is empty because of searching.
=> Close issue #33

qml/FileListPage.qml
As explained in https://sailfishos.org/develop/docs/silica/sailfish-application-pitfalls.html/ I've added a visible attribute to the pull down menu.
=> [office] fix issue #37, by hiding the pulldown menu when no documents.

pdf/pdfcanvas.cpp, pdf/pdfcanvas.h, pdf/pdflinkarea.cpp, pdf/pdflinkarea.h, pdf/pdfrenderthread.cpp, plugin/PDFView.qml
This adds partial support for internal links in PDF documents. It makes the view scrolls to the target page of the link. It should contribute to issue #42. Currently, the inside of the target page itself is not scrolled.
=> [office] Add support for internal Goto link in PDF.

pdf/pdfcanvas.cpp, pdf/pdfcanvas.h, plugin/PDFView.qml
This is a small modification in the paint node method to display a diffused rectangle shape of a page when the page has not been rendered yet. This gives a minimal visual feedback of the position in the document for instance when scrolling fast, or when  going to the next search match several pages further.
=> [office] Add a shape visual for each page that has not been yet rendered.

plugin/CMakeLists.txt, plugin/PDFDocumentPage.qml, plugin/PDFStorage.js, plugin/PDFView.qml
I've taken back the QML + JS implementation of the remember page position PR. I've corrected what has been discussed in #47:
* I've not included the setting page to turn this on and off. It's still dependent on a dconf key, but it's true by default.
* I've moved the handling of SQL storing / restoring from PDFView to the main PDFDocumentPage object. Like that, the PDFView is kept simple stupid (and possibly reusable for simple PDF display).
* The storing is done on page status becoming inactive and on Qt.application sending aboutToQuit. It seems to work like that.
* The restoring is done on a new signal from PDFView that is emitted once when the page sizes of the PDF document have been computed.
Sorry for this feature implementation taking so much review time from you. I appreciate your …
=> [office] Implement persitent storage of page location for PDF documents (QML + JS).

qml/CoverPage.qml
This requires a small change on Sailfish Silica. Thus, left the ```updateCover``` but in practice that could be removed. If everybody agrees, I'd like to drop it already now.
Idea here is that content is grab when peeking starts (cover becomes visible) and released when cover is invisible and application window is visible (in practice at foreground). The releasing part guarantees that the old captured document doesn't flicker on the cover.
In addition, grabbing is done only if application window is visible (main window). Currently you can see errors printed from QQuickItemGrabResultPrivate::create we're trying to grab when main window is already hidden.
=> [sailfish-office] Fix pdf document image grabbing. Contributes to JB#31599

pdf/pdfcanvas.cpp, pdf/pdfcanvas.h, plugin/PDFView.qml
As discussed when dealing with PR #43, link can be quite difficult to tap on, especially for internal goto links that can be used for references with very tiny link box… We agreed then that it could be a good idea to try to find links on closest distance instead of the current implementation of augmented link boxes.
This PR introduces a square distance calculation that equals to zero inside a link box, and equals to the distance to the closest point on the link box border when outside. Then the link is chosen as the one with the closest value on all links within a wiggle room.
To be dpi independant, the wiggle room (which is in pixel in C++) is chosen in QML as the size of an itemSizeMedium / 2, making links easily reachable (they are more or less the size of a thumb with this choice).
=> [office] modify link selection on tap for a better sensivity.

plugin/PDFDocumentPage.qml, rpm/sailfish-office.spec
Minor changes to be in coherence with the rest of password entries in Sailfish.
I've raised the silica version requirement, but without knowing when PasswordField was exactly introduced, I put it to the version currently in SF2.0.1.
I'm wondering if these kinds of minor PR can save your time by just looking at it and accepting (if allright of course), or if you prefer to track these small changes internally ?
=> [office] Use new PasswordField item to unlock PDFs.

plugin/PDFDocumentPage.qml
The two commits should correct two minor issues in the toolbar:
* the icon and the page current / count label are not highlighted when tapped on. The first commit correct this. I decided to make the first Item an IconButton to express the idea that the toolbar contains a button here with an icon, and also a label, thus  I added it as a children.
* the two prev / next buttons of the search result are quickly visible on the bottom left when clicking on the page icon and the page is transitioning to the index page. The commit should correct this by setting the visibility of the buttons only when they are needed.
=> Correct two minor issues in the PDF toolbar.

pdf/pdfrenderthread.cpp
Quite embarassing, I've mixed bottom() and top() for QRectF in last commit for links.
In fact, I've looked at the Qt documentation (5.5 version on the web) and it mentions that top() is equivalent to y(), thus I wrote the previous commit according to this. But I notice an issue (links not working) when the link height is bigger than the wiggle. Debugging on the phone, I noticed that top() is in fact y() + height(). So I don't know if it's a documentation issue on the web or if top() and bottom() were exchanged between Qt5.2 and Qt5.5.
What your opinion ?
[Example of PDF with large links not working currently](https://github.com/sailfishos/sailfish-office/files/106478/CALISTE_DAMIEN-YA6FPQ.pdf)
=> [office] Correct an issue with large links not working.

plugin/DetailsPage.qml, plugin/DocumentPage.qml
The commit 83fd9a1398db747137f0e5caa0a63514a0aaa2e6 that removes the Calligra import in the details page breaks the switch in that page. As a result, the label for the page count is not displayed.
This PR corrects this, not by reintroducing the Calligra import, but by passing the mime type to the detail page and handling this accordingly.
=> [office] Correct missing page label in detail page.

plugin/PDFView.qml
Too big zoom levels might hit texture size limits, leading to rendering failure.
=> [sailfish-office] Restrict zoom level same amount in both orientations. 

pdf/CMakeLists.txt, pdf/pdfcanvas.cpp, pdf/pdfcanvas.h, pdf/pdfdocument.cpp, pdf/pdfdocument.h, pdf/pdflinkarea.cpp, pdf/pdflinkarea.h, pdf/pdfrenderthread.cpp, pdf/pdfrenderthread.h, pdf/pdfselection.cpp, pdf/pdfselection.h, pdf/sailfishofficepdfplugin.cpp, plugin/CMakeLists.txt, plugin/PDFSelectionDrag.qml, plugin/PDFSelectionHandle.qml, plugin/PDFSelectionView.qml, plugin/PDFView.qml
This PR introduces text selection in PDF documents. It is made of four commits:
* first commit makes available in PDFDocument class the list of text boxes for each pages as returned by Poppler.
* second commit implements a QAbstractModelList to expose a portion of the previous list of text boxes for each page. It introduces a method to retrieve a text box at a given point and methods to change the start and stop boundaries for text selection.
* third commits adds a longPress signal to the PDFLinkArea object.
* fourth commit uses all the previous ones to implement the user interface for text selection.
The way text is selected is as followed:
* long press on a word, the word is highlighted and two handles appears to both ends;
* tap and drag a handle (start or stop) to adjust the …
=> Implement text selection in PDF documents

pdf/pdfcanvas.cpp, pdf/pdfcanvas.h, pdf/pdfdocument.cpp, pdf/pdfdocument.h, pdf/pdfjob.cpp, pdf/pdfjob.h, pdf/pdfrenderthread.cpp, pdf/pdfrenderthread.h, plugin/PDFView.qml
There is a TJC question about being able to increase the zoom level for PDFs : https://together.jolla.com/question/1763/unlimited-zoom-needed-in-document-viewer/
The limit is currently hardcoded in PDFView.qml, and set to 2.5. I understand that this limit is used to avoid having too big textures and limit memory consumption. But that would be convenient to be able to change this value anyway, knowing what we're doing. There is even a patch for patch manager to do this : https://openrepos.net/content/ancelad/patch-gallery-image-zoom . The patch, actually, uses a dconf key value instead of the hardcoded 2.5. So like that, one can create a GUI or even change via command line the setting.
The PR, I propose, just changes the hardcoded value for a dconf key (like the idea in the patch). The …
=> [office] Implement partial page rendering to allow unlimited zoom.

pdf/pdfcanvas.cpp, pdf/pdfrenderthread.cpp
When testing the 1310 pages PDF reference document to look for slowing factors, it happens that this PDF file cannot be opened with Poppler 0.24.5 (which is currently on my phone), it gives some errors and reports to have no page.
I notice so that zero-page document handling is broken (infinite loop requesting page size + no way to go back to document list). This PR should fix the two issues by setting the failure flag to doculment when the document has no page.
=> [office] Fix zero page PDF documents.

pdf/pdfdocument.cpp, pdf/pdfdocument.h, pdf/pdfjob.cpp, pdf/pdfjob.h, pdf/pdfrenderthread.cpp, pdf/pdfrenderthread.h, plugin/PDFDocumentPage.qml
Initial implementation of search capability in PDF document is using the job queue that is created to load and render PDF documents. That was done for reasons of simplicity and reuse of existing code. But it has three main drawbacks:
* it is using the rendering thread, so a long search postpone any new rendering job (*i.e.* scrolling while searching does not update the view);
* it is not easily cancellable without adding cancellation in PDFJob class that has no sense for other purposes of PDFJob (except loading maybe). So searches in long documents can last for minutes;
* it can not without additional modifications report search progress.
The present PR corrects the first two points by introducing a new ```SearchThread``` class that is dedicated for search. Like that any code specific to …
=> Make search in PDF cancellable (and not using the rendering thread)

pdf/pdfcanvas.cpp
Should correct issue #83 . The cullprit was the texture that was delete as soon as the PDFCanvas object was delete while they may be used a bit longer by the render thread.
Seems to work, but should be tested further.
=> [office] Postpone texture deletion, avoid crash on quit with busy running.

plugin/CMakeLists.txt, plugin/PDFDocumentPage.qml, plugin/SearchBarItem.qml, plugin/ToolBar.qml
This pull request should match the new ui design for current capabilities of the toolbar, *i.e* page counter and search. The toolbar content is modified to contain BackgroundItem which width are the page width divided by the number of children in the toolbar. Like that, we can later easily add items for highlight and annotate.
* The first commit modifies the page counter to use this new design and also match the design mockups (replace « / » by « | » and don't use any icon).
* The second commit modifies the search tool by introducing a new Item called SearchBar that is a modified version of SearchField.qml (I kept the header for licences reasons) to add the two prev / next buttons and add an iconized state when in the tool bar. Also handle the number of matches with the label property …
=> Design update of the toolbar

plugin/ContextMenuHook.qml
At high zooming factors, when tapping on a link to make the context menu appears, the area becomes black and there are some message in console about texture issues.
This is the old bitting texture limit issue. The width of the ContextMenuHook was too large. It was bind to its parent width, thus having the width of the full PDF.Canvas. When a ContextMenu is attached the effect to remove the diming is applied on the ContextMenu and its parent (here the ContextMenuHook). Thus the oversized texture.
The solution is to bind the width of the ContextMenuHook to the flickable width and shift its horizontal position by contentX. Like that the texture is always guaranteed to be smaller or equal to the screen.
=> [office] Correct the ContextMenuHook not appearing at high zooming factors.

pdf/pdfrenderthread.cpp, pdf/pdfselection.cpp
Broken by 919030e00b51571, Poppler doesn't like numPages() asked from locked document.
Don't have pdf with 0 pages, so didn't test how that continues working. 
@dcaliste
=> Fix crash on password protected pdf files

pdf/pdfcanvas.cpp
98dfd3a610c6 made use deleteLater without checking null pointer.
@dcaliste
=> [office] Avoid warnings for unexpected null receiver. Fixes JB#36476

plugin/PDFDocumentPage.qml
=> [office] Make sure PDF page number's text doesn't go past item area.

plugin/PDFDocumentPage.qml, plugin/PDFView.qml
Add a back button in the toolbar when tapped on an internal goto link, see #89. Also add smooth scroll to the link location.
When tapping on an internal goto link, the view scrolls to the link target location and the toolbar is shown. The toolbar is kept visible, up to the moment the back button is either tapped, the view is scrolled more than the height of a screen, or the zoom changes. Going back to the previous location is also smoothly animated.
=> [office] Add a back button after an internal link has been taped.

plugin/ContextMenuHook.qml, plugin/PDFView.qml
I found a corner case when opening a context menu make the contentY change quickly to an offset position before returning to normal.
To reproduce:
* open a context menu on an external link (like one on the top right corner of the first page of the attached PDF) ;
* tap on a goto link (like the one on the page number, right bottom corner of the first page) ;
* tap on the back arrow and reopen the first context menu again.
The root of this is very hidden. It's the _flickableContentY property of the ContextMenu that triggers this. Following the previous steps:
* after opening the context menu the first time, the ContextMenu exists in memory and is attached to the ContextMenuHook that is taking the place of the link on the first page.
* when tapping on the goto link, the ContextMenuHook is …
=> [office] Correct a blicking artefact happening on a link context menu after back button was pressed.

plugin/SearchBarItem.qml
A little hacky, but does its job.
@jpetrell
=> [office] Fix pdf search string not fully visible on bigger font size.

pdf/pdfdocument.cpp, pdf/pdfdocument.h, pdf/pdfrenderthread.cpp, pdf/pdfrenderthread.h, pdf/pdfsearchmodel.cpp, pdf/pdfsearchmodel.h, plugin/PDFDocumentPage.qml, plugin/PDFView.qml, plugin/SearchBarItem.qml
Implement an incremental text search by signaling every 3 pages the additional matches since the last update. A singular modification is that now the search model advertised by the document is available since the beginning of the request with a zero count. A fraction of the job done is also signaled so one can implement a progress bar.
I had to change various things in the UI because some of the logic in SearchBarItem.qml was based on the assumption that the search model was given at the end of the search and that a count of zero was meaning no match. The clear / cancel button is now also a stop button that can stop the current search while keeping the results already found if pressed when searching.
I think, the biggest other change I made is that the search model is not anymore a …
=> [office] Use incremental search.

pdf/pdfcanvas.cpp, pdf/pdfcanvas.h, pdf/pdfdocument.cpp, pdf/pdfdocument.h, pdf/pdfjob.cpp, pdf/pdfjob.h, pdf/pdfrenderthread.cpp
Try to correct the long loading time of lengthy PDF files (like the PDF reference paper). This loading time is mainly due to the link scanning in all pages and in a smaller proportion to the construction of the table of content.
To remove the link loading time, I've made this done on demand for pages that are displayed and that has not yet retrieved the link rectangles. This works quite well IMHO, the initial loading time being well reduced. But currently there is one issue: the rendering jobs having the priority, the links appear on page after the pages themselves have been rendered.
Do you think this is an issue ? Should I find a way to better interlaced texture rendering and link scanning in the job queue ?
=> [office] Defer link scan on a page on request instead at load time.

pdf/pdfrenderthread.cpp, pdf/pdftocmodel.cpp, pdf/pdftocmodel.h, plugin/PDFDocumentToCPage.qml
Second PR for PDF document load time improvement.
This time, the idea is to move the creation of the table of content model into a dedicated thread, to avoid doing it in the load thread.
The busy indicator and the associated ready property may look a bit overkill, because they almost never appear, but one can see them for the reference pdf document, by taping on the page count in the toolbar. Otherwise, I've never seen them appear…
As a result, the reference PDF document, now opens in the same duration as in Evince on desktop (almost).
=> [office] Delegate table of content build to a dedicated thread.

main.cpp, models/trackerdocumentprovider.cpp
Calligra has tons of debug messages, seems like everything on by default.
Cannot silence just Calligra side separately as lot is done with plain
qDebug instead of the categorized version, so now disabling all but
qml/js debug by default.
@jpetrell @dcaliste
=> Silence debug unless explicitly asked with -d. 

models/trackerdocumentprovider.cpp, plugin/PlainTextDocumentPage.qml, qml/Main.qml
And change the icon, and restrict plain text files in the documents
list to those with a .txt extension.
=> [office] Add a view placeholder for empty text files. JB#45282

plugin/ToolBar.qml
When pulling down the flickable to get the pulley menu, this trigger the toolbar because we are moving "upward".
Disable this in the toolbar itself.
=> [sailfish-office] Hide PDF toolbar when pull down menu is active.

plugin/FullscreenError.qml
Would be nice if Calligra had its translations available, but they
are pain to work with, being located in huge kde subversion repository,
away from the main code. Also everything included would mean
tens of megabytes of data when only a few string are ever shown
to the user on sailfish-office. And even then we'd be forced to show
what Calligra decided as format and available translations.
So let's just hack the few known strings separately for now.
@adenexter @dcaliste @jpetrell
=> Add translation support for some Calligra strings

plugin/PDFDocumentPage.qml
Simple typo making note creation failing, see [TJC](https://together.jolla.com/question/212151/cant-create-notes-in-pdf/).
=> [sailfish-office] Correct note creation not working in PDF documents.  Fixes TJC#212151

plugin/ContextMenuHook.qml, plugin/PDFContextMenuHighlight.qml, plugin/PDFContextMenuText.qml, plugin/PDFDocumentPage.qml
It's a follow-up of #135 after comment from poster on TJC mentioning that notes where not created at the right place.
Testing this, I've found several minor issue with annotation handling after migration to latest design:
* dismissing a long press context menu was making the flickable scroll to top.
* creation and modification of a note from the context menu was doing nothing because of a wrong id in PDFContextMenu*.qml.
* notes created from toolbar were not positioned properly because the 'at' argument was missing the content offsets that existed before.
Quick tests of annotation creation and modification in a zoomed-in document were not showing additional bugs. Maybe @pvuorela or @jpetrell if you have time to test also, you may find something else. Tell me, I'll try to give a look. …
=> Various minor corrections in annotation handling

plugin/IndexButton.qml, plugin/SearchBarItem.qml, plugin/ToolBar.qml
As [reported by @rozgwi on TJC](https://together.jolla.com/question/212568/documents-misaligned-toolbar-on-xperia-x/), the search progress bar was not filling properly up the toolbar height. I'm also pushing an additional commit to correct the page indicator not highlighted on press.
@pvuorela and @jpetrell, during the redesigned, you choose to remove BackgroundItem from toolbar items. I guess it's by design to use only IconButton there. I've one question though: the search icon is still a BackgroundItem and when pressed, it is highlighted with a solid coloured rectangle, while all other icon buttons are not. Should we correct this inconsistency by making SearchBarItem to inherit IconButton instead of BackgroundItem ? Or should we add BackgroundItem to all other IconButtons ?
=> Correct search bar progress not filling-up toolbar height. Contributes TJC#212568

plugin/IndexButton.qml, plugin/PDFDocumentPage.qml
Following discussion in [TJC thread](https://together.jolla.com/question/212568/documents-misaligned-toolbar-on-xperia-x/), I propose to expand a bit the size of the page index in PDF toolbar. For documents with many pages (like more than 100), the current label is shrinking to fit into a itemSizeSmall width.
I propose to expand this to itemSizeMedium, and to avoid to have wider space for documents with few pages (< 10), I'm changing a bit the width calculation logic to (label.implicitWidth + padding) limited by itemSizeMedium.
=> [sailfish-office] Increase the size of the page index in toolbar. Contributes to TJC#212568

pdf/pdfrenderthread.cpp
@pvuorela, sorry I was mistaken with ec21e4eba266f0ad23417970bf2b39c0f4f4211d. It's not fixing the crash issue, I think I was mislead by the fact that it was working in ```gdb``` where I tested. Anyway, the (hopefully) real fix is coming with this PR. Maybe an upgrade in Poppler make that removed annotation are deleted soon than before and we cannot the pointer anymore afterwards. So, I'm saving the bounding box for the signal before removing the annotation.
=> [sailfish-office] Don't use annotation boundary after removal.

plugin/PDFDocumentPage.qml, plugin/SpreadsheetPage.qml, plugin/TextDocumentPage.qml
The maximum zoom level was previously set to 10. On a large screen, a
small file could have a minimum zoom level larger than this. As a
result, the bounds check (min <= zoom <= max) in Calligra's
ViewController::zoom() method always failed, and the zoom became locked
to some initial value.
The overlay tool icons for Spreadsheets are shown only when the document
is at minimum zoom level. Since the minimum zoom level was never
reached, as a side effect the tool icons would never appear.
This change ensures that the maximum zoom level is always larger than
the minimum zoom level, ensuring that zooming is always possible and
that the tools can be made visible.
=> Ensure zooming is always possible, even on a large screen

plugin/DetailsPage.qml, plugin/fileinfo.cpp, plugin/fileinfo.h, qml/Main.qml, rpm/sailfish-office.spec
Also now using full file path as there is more space for it.
FileInfo adjusted a little not to confuse paths and urls.
@jpetrell @saukko
=> [sailfish-office] Use left aligned details page items. Fixes JB#41622

pdf/pdfdocument.cpp
On a very short document it's possible to try adding an annotation
below the document area. Doing that made the app crash.
Now the operation fails silently on the UI side, but should be quite much
better already.
@dcaliste @jpetrell
=> [sailfish-office] Fix crash when adding pdf annotation below the document. Fixes JB#48393

pdf/pdfannotation.cpp
QRectF::united() is const and the code didn't seem to do much.
@dcaliste @llewelld @jpetrell
=> [office] Fix pdf annotation boundary. Fixes JB#48952

pdf/pdfcanvas.cpp
When the layout of a page changes a new PDFPage instance is created, and
the details (including the texture) attached to any existing instance of
the same page are copied over to the new instance. The hasImage flag was
being omitted from the copy, causing the renderer to think there was no
image to use, even when there was. As a result, when zooming into or out
of a page, the existing image (in the wrong resolution, but still
usable) was being lost while the new version was being redrawn.
This change makes it so that the old image is used in a scaled form,
making zooming appear more responsive.
This was a regression introduced in commit
b2c78650cba4688d80533aafda501e68a332c83a
=> Ensure new page layouts re-use existing textures when zooming

plugin/CalligraDocumentPage.qml, rpm/sailfish-office.spec
Use the Page backgroundColor property which is capable of a few more
optimisations instead of the background rectangle in pages.
=> [office] Hide the application background in the homescreen when viewing document pages. Contributes to JB#49705

sailfish-office.desktop
@pvuorela currently, if you open a sharing page inside the application, nothing happens.
=> [sailfish-office] Add sharing to permissions.

sailfish-office.desktop
Notifications are used as information bubble to provide
feedback when adding annotations in PDF files.
Open a PDF and in the toolbar tap on the pen for instance. Doing it should open a minor notification saying that you can highlight text with the finger.
@rainemak and @pvuorela, sorry to be slow ;)
=> [sailfish-office] Add notifications permission.

main.cpp
As discussed from sailfishos/sailjail-permissions#33, I'm changing application name and organisation name for the sailfish-office executable also, so that QML storage can be accessible via sailjail automatically.
I'm not proposing to migrate old database because it's just view settings per document. Not a big deal to loose them during transition.
@Tomin1 and @pvuorela what's your opinion ?
=> [sailfish-office] Update application and organisation name. Fixes JB#52708

sailfish-office.desktop
Allow office to access documents on external data storages.
=> Add RemovableMedia Sailjail permission.

sailfish-office.desktop
Add UserDirs permission to allow sharing from any of those directories.
As Documents and Downloads are part of UserDirs, they are not needed
separately.
=> [office] Add UserDirs permission. JB#54876 OMP#JOLLA-239

config.h.in, main.cpp, models/trackerdocumentprovider.cpp, models/trackerdocumentprovider.h, plugin/sailfishofficeplugin.cpp, rpm/sailfish-office.spec
Switched to libtracker-sparql based driver and implemented a simple graph update api: https://git.sailfishos.org/mer-core/libqtsparql/merge_requests/10
One potentially problematic detail now is that the metadata extraction with Tracker3 seems to start only when needed, i.e. the Documents app launched the first time. At the moment this doesn't recognize the ongoing mining and will say for some time there are no documents on the device. Not sure at the moment what to do with that, but think I'll first adapt the remaining parts to the new tracker, and perhaps could first merge this sort of version anyway.
@llewelld @rainemak @okodron @abranson
=> Migrate to Tracker3 

sailfish-office.desktop
Sharing is allowed by default, separate permission is not needed.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>
=> [sailfish-office] Remove unneeded Sharing permission. JB#55380

models/documentlistmodel.cpp, models/documentlistmodel.h, models/filtermodel.cpp, qml/FileListPage.qml, rpm/sailfish-office.spec
Tracker3 migration switched from (badly working) lastAccessed to lastModified, thus the fileRead/lastRead type of naming doesn't make sense anymore. "Date" matches the sorting option and is more abstract.
@Tomin1 @mlehtima
=> Include %license file and adjust naming slightly

pdf/pdfannotation.cpp
The plain qobject ctor is defined but not implemented. If this was
uncreatable type it could be skipped, but then the
"property PDFAnnotation annotation" type of declarations in qml side
wouldn't work.
There was also partial m_annotation null protection, but not everywhere.
@Tomin1 @rainemak  @dcaliste
=> [sailfish-office] Add missing pdfannotation ctor implementation. Fixes JB#57554

plugin/PDFContextMenuHighlight.qml, plugin/PDFDocumentPage.qml
The Loader was behind the mostly invisible pdf view and thus not getting mouse events. Was not possible to move cursor, change password text visibility or tap the field to get focus back.
Also migrate from deprecated ContextMenu:hide() to close()
@dcaliste @llewelld @Tomin1
=> Fix tap handling on pdf password field. Fixes JB#58742

pdf/CMakeLists.txt, pdf/pdfdocument.cpp, pdf/pdfdocument.h, pdf/pdfjob.cpp, pdf/pdfjob.h, pdf/pdfrenderthread.cpp, pdf/pdfrenderthread.h, plugin/CMakeLists.txt, plugin/DetailsPage.qml, plugin/DocumentHeader.qml, plugin/DocumentPage.qml, plugin/PDFDetailsPage.qml, plugin/PDFDocumentPage.qml, plugin/PresentationDetailsPage.qml, plugin/PresentationPage.qml, plugin/SpreadsheetDetailsPage.qml, plugin/SpreadsheetPage.qml, plugin/TextDetailsPage.qml, plugin/TextDocumentPage.qml, rpm/sailfish-office.spec
@pvuorela I tried to implement via Sailfish Secret a manager for the passwords of protected PDF documents. You can decide to store the password you type, like that it is automatically applied on next opening. In the detail page of PDF documents, you can see the password that is saved for a given document and possibly remove the stored password if you don't want to keep it anymore.
The switch to allow to store the password in the placeholder asking for the password, makes the text field loose the focus, which is sub optimal. I've no idea how to treat this properly for the moment…
=> [sailfish-office] Allow to store PDF passwords.

plugin/PDFDocumentPage.qml
Better if we don't need to rely on system showing these, and also the banner notification is not that nice with display with cutout/notch on top.
=> [sailfish-office] Use in-app notice instead of system notification. JB#62389

.gitignore, models/documentlistmodel.h, models/trackerdocumentprovider.cpp, plugin/CalligraDocumentPage.qml, plugin/ContextMenuHook.qml, plugin/ControllerFlickable.qml, plugin/DetailsPage.qml, plugin/PDFAnnotationEdit.qml, plugin/PDFDocumentPage.qml, plugin/PDFDocumentToCPage.qml, plugin/PDFSelectionView.qml, plugin/PDFView.qml, plugin/PlainTextDocumentPage.qml, plugin/PresentationPage.qml, plugin/PresentationThumbnailPage.qml, plugin/ShareButton.qml, plugin/SpreadsheetPage.qml, plugin/TextDocumentPage.qml, plugin/TextDocumentToCPage.qml, plugin/ToolBar.qml, qml/FileListPage.qml
Main commit:
[sailfish-office] Adjust sparql to work with newer Tracker/Tinysparql. JB#61614
Depending on details, newer versions of Tinysparql (formerly known
as Tracker) might choke on nested SELECTs with same ids.
See https://gitlab.gnome.org/GNOME/tinysparql/-/issues/472
Unclear whether those should work or not but let's now just avoid
=> Adjust sparql to work with newer Tracker/Tinysparql
