sailfishos/sailfish-office

pdf/CMakeLists.txt
pdf/pdfcanvas.cpp
pdf/pdfcanvas.h
pdf/pdfdocument.cpp
pdf/pdfdocument.h
pdf/pdfjob.cpp
pdf/pdfjob.h
pdf/pdfsearchmodel.cpp
pdf/pdfsearchmodel.h
plugin/CMakeLists.txt
plugin/DocumentPage.qml
plugin/PDFDocumentPage.qml
plugin/PDFDocumentToCPage.qml
plugin/PDFView.qml
plugin/ToolBar.qml

I would like to address (see https://together.jolla.com/question/90317/help-improve-document-application/ ) these issues for PDF documents :
* access to current page number ;
* jump to a given page not in the table of content ;
* search in documents ;
* not easily discoverable table of content page as can be seen in the comment complains in the shop.
I propose as a solution to have a toolbar that is displayed when the document is scrolled up and hidden when document is scrolled down, like in the browser. This toolbar contains a page indicator and a search field. The page indicator opens the index subpage where a goto page entry has been added.

Try to address several usability issues, like page navigation or inline searching for PDF documents.

---

pdf/pdfcanvas.cpp

Change slightly the algorithm to get current page :
* previously, page number correspond to the page the top line of the screen belongs to.
* new implementation, page number is the page with the biggest shown surface, if several have the biggest shown surface, the first to match gives the page number.
This PR is necessary for a later one that is in my last-page branch to save current page when quiting a document. It's better to have a more natural number for the pages.
This new way is much more natural and simply implemented with a strictly superior to previously found biggest area. It has only one drawback that is IMHO not very important since it's a corner case : it will give a false page number in the case where several full pages are visible on the  screen but one of them, near the …

[office] Change the current page value according to biggest page shown instead of top one.

---

pdf/pdfcanvas.cpp
pdf/pdfdocument.cpp
pdf/pdfdocument.h
pdf/pdflinkarea.h
plugin/DocumentPage.qml
plugin/PDFDocumentPage.qml
plugin/PDFView.qml
plugin/PresentationPage.qml
plugin/SpreadsheetPage.qml
plugin/TextDocumentPage.qml
plugin/ToolBar.qml

ViewPlaceHolder didn't really work for these. Now avoiding whole split view if pdf is not loaded.
Some other cleanups and fixes also included.

Adjusted pdf error and locking state UIs 

---

plugin/PDFDocumentPage.qml
plugin/ToolBar.qml

- Refactored Toolbar not to force PDF content clipping
- Added enter key icon for PDF search field

Polish PDF search functionality

---

main.cpp

@pvuorela smallie for easier qml profiler enabling.

Add QML_DEBUGGING_ENABLED env variable to enabling qml debugging / profiling

---

models/trackerdocumentprovider.cpp
pdf/pdfcanvas.cpp
pdf/pdfcanvas.h
pdf/pdfdocument.cpp
pdf/pdfjob.cpp
pdf/pdfjob.h
pdf/pdfrenderthread.cpp
pdf/pdfrenderthread.h
pdf/pdfsearchmodel.cpp
pdf/pdfsearchmodel.h
pdf/pdftocmodel.cpp
plugin/sailfishofficeplugin.cpp

Fix crash + cosmetics

---

plugin/CMakeLists.txt
plugin/PDFContextMenu.qml
plugin/PDFDocumentPage.qml
plugin/PDFView.qml

There is currently a lack in security, in my opinion, when clicking on a link in a PDF document. It opens immediately the browser, without the the user to check that the URL of the link correspond to something he wants to do. I've received recently several fishing attempts by email in attached PDF documents with false links to banks…
This PR is still not really user friendly, I think, but I submit it anyway to start a discussion on the better way to inform the user of URL in links and avoid fishing (but not only). It currently opens a dialog with the URL and open the brozser on dialog acceptance.
What's your opinion on this matter ? I can try to implement a better solution if you think to any or has mockup about this from design, whatever.

[office] Add a dialog to display URL link before opening browser.

---

pdf/pdfcanvas.cpp

The additional request that you were reporting was due to how the shown page were rendered. With the last PR, any page with a visible surface was requesting a size of textureLimit centered on the middle of the visible part of the page. So when a page was rendered with just a small top portion, the requested part may not cover the full page even if a better centered textureLimit would have allow to render the full page anyway.
To be short, this PR adds the notion for the visible pages to request the full page if it fits into texture limit, whatever the visible part size. For areas that don't fit into texture limit, the request is the same than for the last PR, _i.e._ partial rendering centered on visible part.

[office] Avoid to render partial page when full page can fit into limit.

---

pdf/pdfselection.cpp

The previous code to change selection by moving handles does not work in a multi-column document (my bad). It resulted in always moving the selection edge into the first column.
This PR hopefully corrects it. This problem was difficult to tackle that I thought of initially. Currently, the code is scanning all text boxes, classifying them as "after" or "before" the "cursor" position. When a before to after transition is found, the before or after box is returned depending on the value of the position argument of the routine. This works well in a document where the layout go from top to bottom.
But in a multi-column document, the layout goes from top to bottom and returns to top again, several times. Thus it exists several before / after transitions for a given cursor position and deciding …

[Office] Correct text selection in documents with columns.

---

plugin/PDFStorage.js

[sailfish-office] Fix PDF pages not opening with Qt 5.6.

---

pdf/CMakeLists.txt
pdf/pdfannotation.cpp
pdf/pdfannotation.h
pdf/pdfcanvas.cpp
pdf/pdfcanvas.h
pdf/pdfdocument.cpp
pdf/pdfdocument.h
pdf/pdfjob.cpp
pdf/pdfjob.h
pdf/pdflinkarea.cpp
pdf/pdflinkarea.h
pdf/pdfrenderthread.cpp
pdf/pdfrenderthread.h
pdf/pdfselection.cpp
pdf/pdfselection.h
pdf/sailfishofficepdfplugin.cpp
plugin/CMakeLists.txt
plugin/ContextMenuHook.qml
plugin/PDFAnnotationEdit.qml
plugin/PDFAnnotationNew.qml
plugin/PDFContextMenuHighlight.qml
plugin/PDFContextMenuLinks.qml
plugin/PDFContextMenuText.qml
plugin/PDFDocumentPage.qml
plugin/PDFSelectionView.qml
plugin/PDFView.qml
plugin/SearchBarItem.qml
plugin/ToolBar.qml

As discussed in #80 , here is the merge request to add support for highlight and text annotations. I'm using it for days now, and I didn't notice any issues. Maybe, one can start reviewing the C++ code when time is available and leave the UI parts for later, or even for a later PR when improved design will be ready.
What do you think ?

Add support for highlight and linked text annotations

---

plugin/PDFDocumentPage.qml
rpm/sailfish-office.spec

[documents] Use better icons for annotation actions. 

---

plugin/PDFView.qml

Factorise the code in PDFView.qml to use the same scrolling animator for goto link and search matching. This solves also the issue of seing all empty pages scroll when the next match is far away.

[office] Use the same scroll animator as for goto link for search matching.

---

CMakeLists.txt
rpm/sailfish-office.spec
sailfish-office.privileges

Add privileges for account handling

---

plugin/DocumentsSharingList.qml
qml/FileListPage.qml

[sailfish-office] Add share context menu on main page. Fixes JB#41808

---

rpm/sailfish-office.spec

[sailfish-office] Fix theme dependency. Contributes to JB#32401

---

plugin/CMakeLists.txt
plugin/FullscreenError.qml
plugin/PresentationPage.qml
plugin/SpreadsheetPage.qml
plugin/TextDocumentPage.qml

Depends on:
https://git.merproject.org/mer-core/calligra/merge_requests/9
WIP at this point. Wanted to quickly try out at this point how my earlier error reporting gets to the app side. Already a lot better than the existing error reporting.

[sailfish-office] Add custom error UI for calligra documents. 

---

plugin/ToolBar.qml

[sailfish-office] Fix broken toolbar on text document viewers. Fixes JB#46943

---

plugin/PDFDocumentPage.qml
plugin/TextDocumentPage.qml

Previous commits had header errors, this fixes them.

[documents] Fix copyright headers. Contributes to JB#47527

---

CMakeLists.txt
models/documentlistmodel.cpp
models/documentlistmodel.h
models/filtermodel.cpp
models/filtermodel.h
qml/FileListPage.qml
qml/SortTypeSelectionPage.qml

- Added a dialog which allows user to select sort parameter: name, type or date
- Added user, name and date sort for file list items

[sailfish-office] Add name, date and type sort in file list. Fixes JB#47911

---

plugin/TextDocumentToCPage.qml
qml/FileListPage.qml
qml/SortTypeSelectionPage.qml

Translate page title

---

models/documentlistmodel.cpp
models/trackerdocumentprovider.cpp

Make csv files visible in document list

[sailfish-office] Open csv files as spreadsheet documents. Contributes JB#46745

---

plugin/PresentationPage.qml
plugin/SpreadsheetPage.qml
plugin/TextDocumentPage.qml

Open documents as read-only to avoid loading editor UI.

---

main.cpp

Comparing boolean with 0 even worked, but let's rather compare just
integers.
@jpetrell  @llewelld

[sailfish-office] Fix bogus comparison. Contributes to JB#38781

---

pdf/pdfcanvas.cpp
plugin/PlainTextDocumentPage.qml

Better plain text link colors + pdf link fix

---

models/trackerdocumentprovider.cpp

Added some error handling and deleting now the results which is callers
responsibility.
@abranson

[sailfish-office] Fix memory leak on tracker results. 

---

CMakeLists.txt
dbusadaptor.h
main.cpp
org.sailfishos.Office.service
org.sailfishos.Office.xml
pdf/pdfjob.cpp
sailfish-office-openfile.desktop
sailfish-office.desktop

Rename org.sailfish.office to org.sailfishos.Office.
This is done to unify bus names and make this more compatible with
application sandboxing. Also changes sailfish to sailfishos in D-Bus
path.

Change bus name to org.sailfishos.Office

---

org.sailfishos.Office.service

Use invoker for correct cgroup delegation on D-Bus activation.

[sailfish-office] Use invoker on D-Bus activation. Contributes to JB#52187

---

org.sailfishos.Office.service

All that this does is that it shows cover but that's now sailjail's job.

[sailfish-office] Drop --desktop-file from D-Bus service invoker args. Contributes to JB#52187

---

plugin/plaintextmodel.cpp

Size checks depend on having access to the file.
@adenexter

[office] Report error on opening a text file. Fixes JB#53526

---

plugin/PDFDocumentPage.qml
plugin/ShareButton.qml
qml/FileListPage.qml

The sharing UI is now launched out-of-process.

[sailfish-office] Adapt to sharing UI and API changes. JB#53987 OMP#JOLLA-75

---

.gitignore
plugin/PDFDocumentPage.qml
plugin/PDFView.qml

Migrate to current nemo qml plugin names

---

plugin/ContextMenuHook.qml
plugin/DetailsPage.qml
plugin/DocumentFlickable.qml
plugin/DocumentHeader.qml
plugin/IndexButton.qml
plugin/OverlayToolbar.qml
plugin/PDFAnnotationEdit.qml
plugin/PDFAnnotationNew.qml
plugin/PDFContextMenuHighlight.qml
plugin/PDFContextMenuLinks.qml
plugin/PDFContextMenuText.qml
plugin/PDFDocumentPage.qml
plugin/PDFSelectionHandle.qml
plugin/PDFStorage.js
plugin/PDFView.qml
qml/CoverPage.qml
qml/FileListPage.qml
rpm/sailfish-office.spec

Fix position of the icon if PageHeader uses some extra margins.
Did a quick round of minor adjustments while at it.

Document header icon position.  JB#62091
